# supabase/config.toml
[project]
id = "lwqajokojdrktzkptzrt"
name = "meek-flutter-app"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

# Edge Functions settings
[functions]
enabled = true
